version: "3"
services: 
  frontend:
    build: # 개발환경을 위한 도커파일이 어디있는지 알려주는 역할
      dockerfile: Dockerfile.dev
      context: ../web-frontend
    volumes: 
      - /app/node_modules # WORKDIR이 app이라서
      - ../web-frontend:/app
    stdin_open: true
    
  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ../nginx
    ports: 
      - "3000:80" # local에 3000, container 안에 80번 port mapping
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ../backend
    container_name: app_backend
    volumes: 
      - /app/node_modules
      - ../backend:/app
  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports: 
  #     - "3306:3306"
  #   volumes: 
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment: 
  #     MYSQL_ROOT_PASSWORD: sqaurelu
  #     MYSQL_DATABASE: myapp